version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: project_nginx
    restart: always
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - project

  app:
    build: ./docker/php
    container_name: project_app
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    networks:
      - project

  mysql:
    image: mysql:5.7
    container_name: project_mysql
    restart: always
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - project
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

networks:
  project:
    driver: bridge